.TH FUELCORE 1 "May 2025" "fuel project" "User Commands"
.SH NAME
fuelcore \- execute and test fuel engine projects

.SH SYNOPSIS
.B fuelcore
[\fIOPTIONS\fR] [\fIFILE\fR]

.SH DESCRIPTION
\fBfuelcore\fR is a command-line tool for running game projects developed with the fuel engine.  
It executes a fuel source file in the current directory.

This tool is intended for use in development, debugging, and profiling workflows.  
It provides lightweight runtime support for games written in \fBFuelLang\fR.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display usage information and exit.

.TP
.B \-v, \-\-version
Show version details and exit.

.SH EXAMPLES
.TP
Run the default fuel project in the current directory:
.B
fuelcore

.SH SEE ALSO
.BR fuel (1),
.BR fuellang (1)

.SH AUTHOR
Written by Awe Morris.

.SH COPYRIGHT
Copyright © 2025 Awe Morris.  
This is free software; see the source for copying conditions.  
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
