FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libx11-dev \
        libxpm-dev \
	libgl1-mesa-dev \
        mesa-common-dev \
        libasound2-dev \
	libgstreamer1.0-dev
